WINDOW_TITLE = "Adventure"
"""Title of the main window."""

SCALE = 2.0
"""The global scale for all textures."""

TILE_SIZE = 32
"""After scaling, the size of a tile."""

PLAYER_MOVEMENT_SPEED = 4
"""Speed of the player, in pixels per frame."""

SPINNER_MOVEMENT_SPEED = 3
"""Speed of the spinners, in pixels per frame."""

MAX_WINDOW_WIDTH = 14 * TILE_SIZE
MAX_WINDOW_HEIGHT = 14 * TILE_SIZE

BOOMERANG_SPEED = 8
BOOMERANG_MAX_DISTANCE = 8 * TILE_SIZE

BAT_MOVEMENT_SPEED = 1.5
BAT_MOVEMENT_RADIUS = 70
SWITCH_SCALE = 0.25
HOLE_DEATH_RADIUS = TILE_SIZE // 2
CAMERA_MARGIN_X = 40
CAMERA_MARGIN_Y = 30

SWORD_ATTACK_DURATION = 0.30
SWORD_HITBOX_SIZE = TILE_SIZE
SWORD_HITBOX_OFFSET = TILE_SIZE

WEAPON_ICON_X = 24
WEAPON_ICON_TOP_MARGIN = 24
WEAPON_ICON_SCALE = 1.0

SCORE_TEXT_X = 60
SCORE_TEXT_TOP_MARGIN = 30
SCORE_TEXT_SIZE = 16

BLOB_PATROL_RADIUS = 3
BLOB_MOVEMENT_SPEED = 1.0
BLOB_ARRIVAL_THRESHOLD = 4.0
BLOB_LINE_OF_SIGHT_MAX = 5 * TILE_SIZE
BLOB_NAVMESH_SUBDIVISIONS = 3
