[project]
name = "projet-icc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "arcade>=3.3.3",
    "networkx>=3.6.1",
    "ruamel.yaml>=0.18.6",
    "types-networkx>=3.6.1.20260408",
]
[tool.ruff.lint]
select = ["ANN"]

[dependency-groups]
dev = [
    "matplotlib>=3.10.9",
    "pytest>=9.0.3",
    "ruff>=0.15.4",
    "snakeviz>=2.2.2",
    "ty>=0.0.19",
]
